---
process_documents_task:
  description: Allow users to upload PDFs, CSVs, or TXT files and read their contents for processing by specialized agents.
  expected_output: Document contents are successfully read and prepared as raw text for fact and concept extraction.
  async_execution: false
  agent: document_processor

extract_facts_task:
  description: Extract all specific, verifiable facts, data points, and key statements from the processed document content, ensuring every truth is captured for the specialist LLM.
  expected_output: A comprehensive list of structured facts extracted from the document, ready for Q&A generation.
  async_execution: false
  agent: fact_extractor
  context:
    - process_documents_task

extract_concepts_task:
  description: Identify and define all key concepts, topics, and important terms within the document content, including their relationships and domain.
  expected_output: A comprehensive list of structured concepts extracted from the document, ready for Q&A generation.
  async_execution: false
  agent: concept_extractor
  context:
    - process_documents_task

generate_qa_pairs_task:
  description: Generate diverse, high-quality, and non-repetitive instruction-input-output pairs in Alpaca format from extracted facts and concepts, engaging in iterative refinement with the Manager Agent.
  expected_output: A set of high-quality Alpaca format Q&A pairs, refined through iterative feedback, ready for quality evaluation.
  async_execution: false
  agent: qa_generator
  context:
    - extract_facts_task
    - extract_concepts_task

evaluate_qa_quality_task:
  description: Rigorously evaluate the quality of generated Q&A pairs, providing detailed feedback for iterative improvement and ensuring only the highest quality data is retained for training.
  expected_output: Validated and filtered high-quality Alpaca Q&A pairs, with feedback provided for any rejected examples.
  async_execution: false
  agent: quality_evaluator
  context:
    - generate_qa_pairs_task

run_llm_shootout_task:
  description: Conduct a "shoot-out" evaluation of various LLMs on specific data generation tasks, score their performance, and record results for the Manager Agent's dynamic selection. This task can be initiated by the user to benchmark models.
  expected_output: Performance scores for tested LLMs on various tasks, stored in the LLM performance registry for future reference by the Manager Agent.
  async_execution: false
  agent: llm_tester

orchestrate_data_generation:
  description: Orchestrate the entire synthetic data generation workflow, dynamically selecting LLMs, managing iterative refinement, and ensuring high-quality Alpaca training data is produced. This is the main task for the Manager Agent.
  expected_output: A comprehensive, high-quality Alpaca format training dataset is generated, optimized through intelligent LLM selection and iterative refinement, ready for LLM training.
  async_execution: false
  agent: manager_agent
  context:
    - process_documents_task
    - extract_facts_task
    - extract_concepts_task
    - generate_qa_pairs_task
    - evaluate_qa_quality_task
